kind: Pod
apiVersion: v1
metadata: 
  name: pod-with-label
  labels:
    type: frontend
    env: prod
spec:
  containers:
  - image: aamirpinger/helloworld
    name: container1
    ports:
    - containerPort: 80
